// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: trip/v1/trip.proto

package tripv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PreviewTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartLocation *Coordinate            `protobuf:"bytes,2,opt,name=start_location,json=startLocation,proto3" json:"start_location,omitempty"`
	EndLocation   *Coordinate            `protobuf:"bytes,3,opt,name=end_location,json=endLocation,proto3" json:"end_location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewTripRequest) Reset() {
	*x = PreviewTripRequest{}
	mi := &file_trip_v1_trip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewTripRequest) ProtoMessage() {}

func (x *PreviewTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trip_v1_trip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewTripRequest.ProtoReflect.Descriptor instead.
func (*PreviewTripRequest) Descriptor() ([]byte, []int) {
	return file_trip_v1_trip_proto_rawDescGZIP(), []int{0}
}

func (x *PreviewTripRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PreviewTripRequest) GetStartLocation() *Coordinate {
	if x != nil {
		return x.StartLocation
	}
	return nil
}

func (x *PreviewTripRequest) GetEndLocation() *Coordinate {
	if x != nil {
		return x.EndLocation
	}
	return nil
}

type PreviewTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Route         *Route                 `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	RideFare      []*RideFare            `protobuf:"bytes,3,rep,name=ride_fare,json=rideFare,proto3" json:"ride_fare,omitempty"` // Array of fares [fares for van, fares for luxury, ..]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewTripResponse) Reset() {
	*x = PreviewTripResponse{}
	mi := &file_trip_v1_trip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewTripResponse) ProtoMessage() {}

func (x *PreviewTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trip_v1_trip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewTripResponse.ProtoReflect.Descriptor instead.
func (*PreviewTripResponse) Descriptor() ([]byte, []int) {
	return file_trip_v1_trip_proto_rawDescGZIP(), []int{1}
}

func (x *PreviewTripResponse) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *PreviewTripResponse) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *PreviewTripResponse) GetRideFare() []*RideFare {
	if x != nil {
		return x.RideFare
	}
	return nil
}

type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Geometry      []*Geometry            `protobuf:"bytes,1,rep,name=geometry,proto3" json:"geometry,omitempty"` // Array of Geometry
	Distance      float64                `protobuf:"fixed64,2,opt,name=distance,proto3" json:"distance,omitempty"`
	Duration      float64                `protobuf:"fixed64,3,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_trip_v1_trip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_trip_v1_trip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_trip_v1_trip_proto_rawDescGZIP(), []int{2}
}

func (x *Route) GetGeometry() []*Geometry {
	if x != nil {
		return x.Geometry
	}
	return nil
}

func (x *Route) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *Route) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type Geometry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coordinates   []*Coordinate          `protobuf:"bytes,1,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Geometry) Reset() {
	*x = Geometry{}
	mi := &file_trip_v1_trip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Geometry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Geometry) ProtoMessage() {}

func (x *Geometry) ProtoReflect() protoreflect.Message {
	mi := &file_trip_v1_trip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Geometry.ProtoReflect.Descriptor instead.
func (*Geometry) Descriptor() ([]byte, []int) {
	return file_trip_v1_trip_proto_rawDescGZIP(), []int{3}
}

func (x *Geometry) GetCoordinates() []*Coordinate {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

type Coordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longtitude    float64                `protobuf:"fixed64,2,opt,name=longtitude,proto3" json:"longtitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	mi := &file_trip_v1_trip_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_trip_v1_trip_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_trip_v1_trip_proto_rawDescGZIP(), []int{4}
}

func (x *Coordinate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Coordinate) GetLongtitude() float64 {
	if x != nil {
		return x.Longtitude
	}
	return 0
}

type RideFare struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId            string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PackageSlug       string                 `protobuf:"bytes,3,opt,name=package_slug,json=packageSlug,proto3" json:"package_slug,omitempty"`
	TotalPriceInCents float64                `protobuf:"fixed64,4,opt,name=total_price_in_cents,json=totalPriceInCents,proto3" json:"total_price_in_cents,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RideFare) Reset() {
	*x = RideFare{}
	mi := &file_trip_v1_trip_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RideFare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideFare) ProtoMessage() {}

func (x *RideFare) ProtoReflect() protoreflect.Message {
	mi := &file_trip_v1_trip_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideFare.ProtoReflect.Descriptor instead.
func (*RideFare) Descriptor() ([]byte, []int) {
	return file_trip_v1_trip_proto_rawDescGZIP(), []int{5}
}

func (x *RideFare) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RideFare) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RideFare) GetPackageSlug() string {
	if x != nil {
		return x.PackageSlug
	}
	return ""
}

func (x *RideFare) GetTotalPriceInCents() float64 {
	if x != nil {
		return x.TotalPriceInCents
	}
	return 0
}

var File_trip_v1_trip_proto protoreflect.FileDescriptor

const file_trip_v1_trip_proto_rawDesc = "" +
	"\n" +
	"\x12trip/v1/trip.proto\x12\atrip.v1\"\xa1\x01\n" +
	"\x12PreviewTripRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12:\n" +
	"\x0estart_location\x18\x02 \x01(\v2\x13.trip.v1.CoordinateR\rstartLocation\x126\n" +
	"\fend_location\x18\x03 \x01(\v2\x13.trip.v1.CoordinateR\vendLocation\"\x84\x01\n" +
	"\x13PreviewTripResponse\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12$\n" +
	"\x05route\x18\x02 \x01(\v2\x0e.trip.v1.RouteR\x05route\x12.\n" +
	"\tride_fare\x18\x03 \x03(\v2\x11.trip.v1.RideFareR\brideFare\"n\n" +
	"\x05Route\x12-\n" +
	"\bgeometry\x18\x01 \x03(\v2\x11.trip.v1.GeometryR\bgeometry\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x01R\bdistance\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x01R\bduration\"A\n" +
	"\bGeometry\x125\n" +
	"\vcoordinates\x18\x01 \x03(\v2\x13.trip.v1.CoordinateR\vcoordinates\"H\n" +
	"\n" +
	"Coordinate\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1e\n" +
	"\n" +
	"longtitude\x18\x02 \x01(\x01R\n" +
	"longtitude\"\x87\x01\n" +
	"\bRideFare\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fpackage_slug\x18\x03 \x01(\tR\vpackageSlug\x12/\n" +
	"\x14total_price_in_cents\x18\x04 \x01(\x01R\x11totalPriceInCents2W\n" +
	"\vTripService\x12H\n" +
	"\vPreviewTrip\x12\x1b.trip.v1.PreviewTripRequest\x1a\x1c.trip.v1.PreviewTripResponseB\x1dZ\x1bshared/proto/trip/v1;tripv1b\x06proto3"

var (
	file_trip_v1_trip_proto_rawDescOnce sync.Once
	file_trip_v1_trip_proto_rawDescData []byte
)

func file_trip_v1_trip_proto_rawDescGZIP() []byte {
	file_trip_v1_trip_proto_rawDescOnce.Do(func() {
		file_trip_v1_trip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trip_v1_trip_proto_rawDesc), len(file_trip_v1_trip_proto_rawDesc)))
	})
	return file_trip_v1_trip_proto_rawDescData
}

var file_trip_v1_trip_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_trip_v1_trip_proto_goTypes = []any{
	(*PreviewTripRequest)(nil),  // 0: trip.v1.PreviewTripRequest
	(*PreviewTripResponse)(nil), // 1: trip.v1.PreviewTripResponse
	(*Route)(nil),               // 2: trip.v1.Route
	(*Geometry)(nil),            // 3: trip.v1.Geometry
	(*Coordinate)(nil),          // 4: trip.v1.Coordinate
	(*RideFare)(nil),            // 5: trip.v1.RideFare
}
var file_trip_v1_trip_proto_depIdxs = []int32{
	4, // 0: trip.v1.PreviewTripRequest.start_location:type_name -> trip.v1.Coordinate
	4, // 1: trip.v1.PreviewTripRequest.end_location:type_name -> trip.v1.Coordinate
	2, // 2: trip.v1.PreviewTripResponse.route:type_name -> trip.v1.Route
	5, // 3: trip.v1.PreviewTripResponse.ride_fare:type_name -> trip.v1.RideFare
	3, // 4: trip.v1.Route.geometry:type_name -> trip.v1.Geometry
	4, // 5: trip.v1.Geometry.coordinates:type_name -> trip.v1.Coordinate
	0, // 6: trip.v1.TripService.PreviewTrip:input_type -> trip.v1.PreviewTripRequest
	1, // 7: trip.v1.TripService.PreviewTrip:output_type -> trip.v1.PreviewTripResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_trip_v1_trip_proto_init() }
func file_trip_v1_trip_proto_init() {
	if File_trip_v1_trip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trip_v1_trip_proto_rawDesc), len(file_trip_v1_trip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trip_v1_trip_proto_goTypes,
		DependencyIndexes: file_trip_v1_trip_proto_depIdxs,
		MessageInfos:      file_trip_v1_trip_proto_msgTypes,
	}.Build()
	File_trip_v1_trip_proto = out.File
	file_trip_v1_trip_proto_goTypes = nil
	file_trip_v1_trip_proto_depIdxs = nil
}
